version: '2'

services:
  db:
    build:
      context: ./infra/docker/db
      dockerfile: Dockerfile
    image: quizzical-db
    ports:
      - "5432:5432"
    volumes:
      - quizzical-db-volume:/var/lib/postgresql/data
      - /Users/mduduzikeswa/Documents/dev/mazasoft/projects/quizical/quizzical/backend/db_backups:/db_backups
  backend:
    build:
      context: ./infra/docker/backend
      dockerfile: Dockerfile
    image: quizzical-backend
    ports:
      - "8080:8080"
    environment:
      - QUIZZICAL_DB_USERNAME=quizzical-admin
      - QUIZZICAL_DB_PASS=getmandisagoodatsatmath
      - QUIZZICAL_DB_HOST=quizzical_db
      - QUIZZICAL_DB_PORT=5432
      - QUIZZICAL_DB_NAME=quizzical
      - QUIZZICAL_DB_SCHEMA=quizzical
    links:
     - db:quizzical_db
volumes:
  "quizzical-db-volume":
    external: true
