version: '2'

services:
  db:
    build:
      context: ./infra/docker/db
      dockerfile: Dockerfile
    image: quizzical-db
    ports:
      - "5432:5432"
    volumes:
      - quizzical-db-volume:/var/lib/postgresql/data
      - /Users/mduduzikeswa/Documents/dev/mazasoft/projects/quizical/quizzical/backend/db_backups:/db_backups
  pentaho-ba-server:
    build:
      context: ./infra/docker/docker-pentaho-ba-ce-7.0
      dockerfile: Dockerfile
    image: quizzical-bi-ba
    ports:
      - "5433:5432"
      - "2222:22"
      - "8888:8080"
    environment:
      - Q7L_EDW_DB_USERNAME=quizzical-admin
      - Q7L_EDW_DB_PASS=getmandisagoodatsatmath
      - Q7L_EDW_DB_HOST=q7ledw_db_server
      - Q7L_EDW_DB_PORT=5432
      - Q7L_EDW_DB_NAME=q7ledw
    links:
      - db:q7ledw_db_server
  backend:
    build:
      context: ./infra/docker/backend
      dockerfile: Dockerfile
    image: quizzical-backend
    ports:
      - "8080:8080"
    environment:
      - QUIZZICAL_DB_USERNAME=quizzical-admin
      - QUIZZICAL_DB_PASS=getmandisagoodatsatmath
      - QUIZZICAL_DB_HOST=quizzical_db
      - QUIZZICAL_DB_PORT=5432
      - QUIZZICAL_DB_NAME=quizzical
      - QUIZZICAL_DB_SCHEMA=quizzical
    links:
     - db:quizzical_db
volumes:
  "quizzical-db-volume":
    external: true
