version: '2'

services:
  api:
    build:
      context: ..
      dockerfile: infra/images/api/Dockerfile
    image: gauntlet-api
    depends_on:
      - db
      - migrator
    ports:
      - "3000:3000"
    volumes:
      - ..:/go/src/github.com/skeswa/gauntlet
      - gauntlet-image-volume:/gauntlet/images
  db:
    build:
      context: ./images/db
      dockerfile: Dockerfile
    image: gauntlet-db
    ports:
      - "5432:5432"
    volumes:
      - gauntlet-db-volume:/var/lib/postgresql/data
  migrator:
    build:
      context: ..
      dockerfile: infra/images/migrator/Dockerfile
    image: gauntlet-migrator
    depends_on:
      - db
    volumes:
      - ../migrator/migrations:/gauntlet/migrations
  web:
    build:
      context: ./images/web
      dockerfile: Dockerfile
    image: gauntlet-web
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ../web:/web
volumes:
  "gauntlet-db-volume":
    external: true
  "gauntlet-image-volume":
    external: true
