backend:
  environment:
    - OSGI_SERVICE_HTTP_PORT=8082
    - OSGI_SHELL_TELNET_IP=localhost
    - OSGI_SHELL_TELNET_MAXCONN=-1
    - OSGI_SHELL_TELNET_PORT=6666
    - QUIZZICAL_DB_HOST=db
    - QUIZZICAL_DB_NAME=quizzical
    - QUIZZICAL_DB_PASS=getmandisagoodatsatmath
    - QUIZZICAL_DB_PORT=5432
    - QUIZZICAL_DB_SCHEMA=quizzical
    - QUIZZICAL_DB_USERNAME=quizzical-admin
    - 'VIRTUAL_HOST=www.q7l.io,q7l.io'
    - VIRTUAL_PORT=8082
    - VIRTUAL_URL=/api/
  image: 'mazagroup/quizzical-backend:latest'
  links:
    - db
  ports:
    - '8082:8082'
db:
  image: 'mazagroup/quizzical-db:latest'
  ports:
    - '5432:5432'
  volumes:
    - '/quizzical-db-volume:/var/lib/postgresql/data'
frontend:
  environment:
    - OSGI_SERVICE_HTTP_PORT=8080
    - OSGI_SHELL_TELNET_IP=localhost
    - OSGI_SHELL_TELNET_MAXCONN=-1
    - OSGI_SHELL_TELNET_PORT=6666
    - 'VIRTUAL_HOST=www.q7l.io,q7l.io'
    - VIRTUAL_PORT=8080
    - VIRTUAL_URL=/
  image: 'mazagroup/quizzical-frontend:latest'
  ports:
    - '8080:8080'
nginx-proxy:
  image: 'tozd/nginx-proxy:latest'
  ports:
    - '80:80'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
